# Generated by Django 2.0 on 2020-01-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('red_orange', 'Red Orange'), ('sky_blue', 'Sky Blue'), ('violet', 'Violet'), ('white', 'White'), ('yellow', 'Yellow'), ('yellow_green', 'Yellow Green')], max_length=30)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], max_length=30)),
                ('shape', models.CharField(choices=[('rectangle', 'Rectangle'), ('ellipse', 'Ellipse'), ('diamond', 'Diamond'), ('trapezoid', 'Trapezoid'), ('parallelogram', 'Parallelogram'), ('triangle', 'Triangle'), ('circle', 'Circle')], max_length=30)),
                ('cost', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
